project:
  type: website
  output-dir: docs
  render:
  - index.qmd
  - research.qmd
  - impressum.qmd
  - teaching.qmd
  - CV.qmd
  - contact.qmd

website:
  title: "Paul Kindermann"
  navbar:
    left:
      - href: research.qmd
        text: Research
      - href: CV.qmd
        text: CV
      - href: teaching.qmd
        text: Teaching
      - href: contact.qmd
        text: Contact
    
  page-footer:
    left: "© 2024 Paul A Kindermann"
    right: 
      - text: "Imprint & disclaimer"
        href: impressum.qmd

format:
  html:
    theme:
    - litera
    - custom.scss

editor: visual

