---
title: ""
---
## Teaching

I have taught undergraduate seminars on the EU, public policy, and political philosophy at the LSE Department of Government, Goethe University Frankfurt, and the University of Hamburg. I am also an Associate Fellow of AdvanceHE in the UK (AFHEA).

#### [London School of Economics and Political Science](https://www.lse.ac.uk/government){target="_blank"}

**Government, Politics and Public Policy in the EU (GV251)**\
Graduate Teaching Assistant (GTA), Undergraduate course (2nd year), lecturer: Prof. Sara Hobolt\
Seminar teaching; designing class and learning activities; formative and summative marking\
*Nominated for LSE SU Teaching Award in ‘Excellent feedback and communication’ and ‘Outstanding teaching’*

#### [Goethe University Frankfurt](https://www.uni-frankfurt.de/43952869/ENGLISH){target="_blank"}
**Introduction to Philosophy**\
Undergraduate course, Teaching Assistant (TA), lecturer: Prof. Martin Seel

#### [University of Hamburg](https://www.philosophie.uni-hamburg.de/en.html){target="_blank"}
**Introduction to Political Philosophy**\
**Introduction to Ethics**\
Undergraduate courses, Teaching Assistant (TA), lecturer: Prof. Arndt Pollmann
